export const consolidatedProviders = [
  {
    id: "provider-001",
    name: "נטע ברסלר - אומני החושים",
    businessName: "נטע ברסלר - אומני החושים",
    description: "אומן חושים מקצועי המתמחה בקריאת מחשבות ואשליות מרהיבות לכל סוגי האירועים",
    categories: ["cat-008"],
    contactPerson: "נטע ברסלר",
    contact_person: "נטע ברסלר",
    email: "neta@example.com",
    contact_email: "neta@example.com",
    phone: "050-1234567",
    contact_phone: "050-1234567",
    rating: 4.9,
    reviewCount: 156,
    review_count: 156,
    featured: true,
    verified: true,
    is_verified: true,
    calendarActive: true,
    address: "תל אביב",
    city: "תל אביב",
    logo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    logo_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    specialties: ["קריאת מחשבות", "אשליות", "מנטליזם"],
    yearsExperience: 8
  },
  {
    id: "provider-002", 
    name: "להקת הזמר דני כהן",
    businessName: "להקת הזמר דני כהן",
    description: "להקה מקצועית לאירועים פרטיים ועסקיים עם רפרטואר מגוון",
    categories: ["cat-001"],
    contactPerson: "דני כהן",
    contact_person: "דני כהן",
    email: "danny@example.com",
    contact_email: "danny@example.com",
    phone: "050-2345678",
    contact_phone: "050-2345678",
    rating: 4.7,
    reviewCount: 89,
    review_count: 89,
    featured: true,
    verified: true,
    is_verified: true,
    calendarActive: true,
    address: "ירושלים",
    city: "ירושלים",
    logo: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=150&h=150&fit=crop&crop=face",
    logo_url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=150&h=150&fit=crop&crop=face",
    specialties: ["מוזיקה עברית", "מוזיקה עולמית", "שירה חיה"],
    yearsExperience: 12
  },
  {
    id: "provider-003",
    name: "סטודיו לצילום אירועים - אורן כהן",
    businessName: "סטודיו לצילום אירועים - אורן כהן",
    description: "צילום מקצועי לאירועים פרטיים ועסקיים עם דגש על רגעים מיוחדים",
    categories: ["cat-005"],
    contactPerson: "אורן כהן",
    contact_person: "אורן כהן",
    email: "oren@example.com",
    contact_email: "oren@example.com",
    phone: "050-3456789",
    contact_phone: "050-3456789",
    rating: 4.8,
    reviewCount: 102,
    review_count: 102,
    featured: false,
    verified: true,
    is_verified: true,
    calendarActive: false,
    address: "חיפה",
    city: "חיפה",
    logo: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&h=150&fit=crop&crop=face",
    logo_url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&h=150&fit=crop&crop=face",
    specialties: ["צילום סטילס", "צילום וידאו", "עריכת תמונות"],
    yearsExperience: 10
  },
  {
    id: "provider-004",
    name: "קייטרינג גורמה - טעם של פעם",
    businessName: "קייטרינג גורמה - טעם של פעם",
    description: "קייטרינג איכותי עם מגוון מנות גורמה לאירועים קטנים וגדולים",
    categories: ["cat-010"],
    contactPerson: "רונית לוי",
    contact_person: "רונית לוי",
    email: "ronit@example.com",
    contact_email: "ronit@example.com",
    phone: "050-4567890",
    contact_phone: "050-4567890",
    rating: 4.6,
    reviewCount: 75,
    review_count: 75,
    featured: true,
    verified: false,
    is_verified: false,
    calendarActive: true,
    address: "ראשון לציון",
    city: "ראשון לציון",
    logo: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=150&h=150&fit=crop&crop=face",
    logo_url: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=150&h=150&fit=crop&crop=face",
    specialties: ["מנות גורמה", "קייטרינג חלבי", "קייטרינג בשרי"],
    yearsExperience: 15
  },
  {
    id: "provider-005",
    name: "DJ אלי - מוסיקה לאירועים",
    businessName: "DJ אלי - מוסיקה לאירועים",
    description: "די ג'יי מקצועי עם ניסיון רב במוסיקה לאירועים פרטיים ועסקיים",
    categories: ["cat-001"],
    contactPerson: "אלי כהן",
    contact_person: "אלי כהן",
    email: "eli@example.com",
    contact_email: "eli@example.com",
    phone: "050-5678901",
    contact_phone: "050-5678901",
    rating: 4.5,
    reviewCount: 120,
    review_count: 120,
    featured: false,
    verified: true,
    is_verified: true,
    calendarActive: true,
    address: "בת ים",
    city: "בת ים",
    logo: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&h=150&fit=crop&crop=face",
    logo_url: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&h=150&fit=crop&crop=face",
    specialties: ["מוסיקה אלקטרונית", "מוסיקה לטקסים", "הגברה ותאורה"],
    yearsExperience: 7
  }
];
