import { SearchResultService, ProviderProfile, Review } from "@/lib/types";

// Expanded mock search results with 50+ services
export const expandedMockSearchResults: SearchResultService[] = [
  // אמני חושים - נטע ברסלר
  {
    id: "service1",
    name: "אומנות המנטליזם עם נטע ברסלר",
    provider: "נטע ברסלר",
    providerId: "provider1",
    description: "מופע מרהיב של קריאת מחשבות ומנטליזם מותאם לאירועים עסקיים ופרטיים",
    price: 3500,
    priceUnit: "לאירוע",
    rating: 4.9,
    reviewCount: 124,
    imageUrl: "https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "אמני חושים",
    location: "מרכז",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-8"],
    featured: true
  },
  // קליספרו - אמן חושים
  {
    id: "service4",
    name: "קליספרו - קסמים ואשליות",
    provider: "דן קליספרו",
    providerId: "provider4",
    description: "מופע קסמים מדהים ואינטראקטיבי לכל הגילאים",
    price: 2800,
    priceUnit: "לאירוע",
    rating: 4.9,
    reviewCount: 92,
    imageUrl: "https://images.unsplash.com/photo-1537074142379-4ce9d4cd7901?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "אמני חושים",
    location: "כל הארץ",
    suitableFor: ["concept-1", "concept-3", "concept-5", "concept-8"],
    featured: true
  },
  // להקות ונגנים
  {
    id: "service2",
    name: "להקת מלודי מייקרס",
    provider: "מלודי מייקרס",
    providerId: "provider2",
    description: "להקה מקצועית לאירועים עם רפרטואר עשיר וביצועים מרהיבים",
    price: 4500,
    priceUnit: "לאירוע",
    rating: 4.8,
    reviewCount: 87,
    imageUrl: "https://images.unsplash.com/photo-1501612780327-45045538702b?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "להקות",
    location: "כל הארץ",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6"]
  },
  {
    id: "service51",
    name: "שיר ישראלי - זמרת",
    provider: "שיר ישראלי",
    providerId: "provider51",
    description: "זמרת מקצועית עם רפרטואר עשיר המתאים לכל סוגי האירועים",
    price: 2500,
    priceUnit: "למופע",
    rating: 4.7,
    reviewCount: 63,
    imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "זמרים",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6", "concept-8"]
  },
  {
    id: "service52",
    name: "רביעיית המיתרים הקלאסית",
    provider: "רביעיית אלגרו",
    providerId: "provider52",
    description: "רביעיית מיתרים מקצועית לאירועים אלגנטיים",
    price: 3200,
    priceUnit: "למופע",
    rating: 4.9,
    reviewCount: 41,
    imageUrl: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "נגנים",
    location: "מרכז וצפון",
    suitableFor: ["concept-2", "concept-5", "concept-6", "concept-10"]
  },
  // קייטרינג ושירותי מזון
  {
    id: "service3",
    name: "קייטרינג מעדני גורמה",
    provider: "מעדני גורמה",
    providerId: "provider3",
    description: "חוויה קולינרית עשירה לאירועים בכל סדר גודל עם תפריט מגוון ומיוחד",
    price: 120,
    priceUnit: "למנה",
    rating: 4.7,
    reviewCount: 156,
    imageUrl: "https://images.unsplash.com/photo-1555244162-803834f70033?w=800&auto=format&fit=crop",
    category: "שירותי מזון ומשקאות",
    subcategory: "קייטרינג בשרי",
    location: "מרכז וירושלים",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6", "concept-8"]
  },
  {
    id: "service53",
    name: "קייטרינג טבעוני אורגני",
    provider: "טבע המנה",
    providerId: "provider53",
    description: "קייטרינג טבעוני אורגני מושקע לאירועים בריאים",
    price: 95,
    priceUnit: "למנה",
    rating: 4.6,
    reviewCount: 48,
    imageUrl: "https://images.unsplash.com/photo-1564675494207-534705c0d7cd?w=800&auto=format&fit=crop",
    category: "שירותי מזון ומשקאות",
    subcategory: "קייטרינג חלבי",
    location: "מרכז",
    suitableFor: ["concept-1", "concept-4", "concept-5", "concept-7"]
  },
  // לוקיישנים
  {
    id: "service7",
    name: "לופט תל אביב",
    provider: "לופט TLV",
    providerId: "provider7",
    description: "לופט מעוצב בלב תל אביב, מתאים לאירועים פרטיים ועסקיים עד 100 איש",
    price: 7000,
    priceUnit: "ליום",
    rating: 4.7,
    reviewCount: 43,
    imageUrl: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&auto=format&fit=crop",
    category: "לוקיישנים ומתחמי אירוח",
    subcategory: "לופטים",
    location: "תל אביב",
    suitableFor: ["concept-4", "concept-5", "concept-7"]
  },
  {
    id: "service54",
    name: "גן אירועים פסטורלי",
    provider: "גני הטבע",
    providerId: "provider54",
    description: "גן אירועים בטבע עם נוף מרהיב לאירועים של עד 250 איש",
    price: 15000,
    priceUnit: "לאירוע",
    rating: 4.8,
    reviewCount: 89,
    imageUrl: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&auto=format&fit=crop",
    category: "לוקיישנים ומתחמי אירוח",
    subcategory: "אולמות אירועים",
    location: "שרון",
    suitableFor: ["concept-1", "concept-2", "concept-5"]
  },
  {
    id: "service55",
    name: "וילה פרטית לאירועים",
    provider: "וילות הים",
    providerId: "provider55",
    description: "וילה יוקרתית עם נוף לים לאירועים אקסקלוסיביים",
    price: 12000,
    priceUnit: "ליום",
    rating: 4.9,
    reviewCount: 36,
    imageUrl: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&auto=format&fit=crop",
    category: "לוקיישנים ומתחמי אירוח",
    subcategory: "וילות אירוח",
    location: "הרצליה",
    suitableFor: ["concept-2", "concept-5", "concept-6", "concept-13"]
  },
  // מתנות ומזכרות
  {
    id: "service11",
    name: "צלמות מגנטים לאירועים",
    provider: "מגנטיקס",
    providerId: "provider11",
    description: "צילומי מגנטים מיוחדים לאירועים עם מגוון אביזרים ורקעים",
    price: 1200,
    priceUnit: "לשעתיים",
    rating: 4.6,
    reviewCount: 87,
    imageUrl: "https://images.unsplash.com/photo-1552334823-ca7f70361452?w=800&auto=format&fit=crop",
    category: "מתנות",
    subcategory: "מגנטים וצילומי מגנט",
    location: "כל הארץ",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-13"]
  },
  {
    id: "service56",
    name: "מתנות ממותגות לעסקים",
    provider: "ברנד גיפט",
    providerId: "provider56",
    description: "מתנות ממותגות איכותיות לאירועי חברה וכנסים",
    price: 30,
    priceUnit: "למתנה",
    rating: 4.5,
    reviewCount: 74,
    imageUrl: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800&auto=format&fit=crop",
    category: "מתנות",
    subcategory: "מתנות ממותגות",
    location: "ארצי",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-11"]
  },
  // צלמים ושירותי הפקה
  {
    id: "service6",
    name: "יעקב הצלם",
    provider: "יעקב כהן",
    providerId: "provider6",
    description: "צילום מקצועי לאירועים פרטיים ועסקיים, כולל עריכה מלאה",
    price: 2200,
    priceUnit: "לאירוע",
    rating: 4.8,
    reviewCount: 112,
    imageUrl: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "צילום סטילס",
    location: "כל הארץ",
    suitableFor: ["concept-1", "concept-2", "concept-3", "concept-5", "concept-8"]
  },
  {
    id: "service57",
    name: "צילום וידאו מקצועי",
    provider: "וידאו פרו",
    providerId: "provider57",
    description: "צילום וידאו מקצועי לאירועים כולל עריכה ותוצר באיכות קולנועית",
    price: 3500,
    priceUnit: "לאירוע",
    rating: 4.9,
    reviewCount: 67,
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "צילום וידאו",
    location: "מרכז וצפון",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-10"]
  },
  // עיצובים ופרחים
  {
    id: "service5",
    name: "עיצובי פרחים פנטזיה",
    provider: "פנטזיה עיצובים",
    providerId: "provider5",
    description: "עיצובי פרחים מרהיבים וייחודיים לכל אירוע",
    price: 1500,
    priceUnit: "בסיס לאירוע",
    rating: 4.6,
    reviewCount: 68,
    imageUrl: "https://images.unsplash.com/photo-1561128290-e900944315fe?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "עיצוב פרחים",
    location: "צפון ומרכז",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6"]
  },
  {
    id: "service58",
    name: "עיצוב אירועים כוכב",
    provider: "כוכב עיצובים",
    providerId: "provider58",
    description: "עיצוב אירועים מלא כולל תאורה, בדים, פרחים ואביזרים",
    price: 5000,
    priceUnit: "לאירוע בסיסי",
    rating: 4.8,
    reviewCount: 53,
    imageUrl: "https://images.unsplash.com/photo-1519741347686-c1e0aadf4611?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "עיצוב אירועים",
    location: "מרכז",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-13"]
  },
  // הגברה ותאורה
  {
    id: "service59",
    name: "הגברה ותאורה מקצועית",
    provider: "סאונד בום",
    providerId: "provider59",
    description: "שירותי הגברה ותאורה מקצועיים לכל סוגי האירועים",
    price: 2800,
    priceUnit: "לאירוע",
    rating: 4.7,
    reviewCount: 82,
    imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "ציוד הגברה",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-4", "concept-5", "concept-10"]
  },
  {
    id: "service60",
    name: "תאורה אווירתית לאירועים",
    provider: "אורות הבמה",
    providerId: "provider60",
    description: "פתרונות תאורה מיוחדים ליצירת אווירה באירועים",
    price: 2200,
    priceUnit: "לאירוע",
    rating: 4.8,
    reviewCount: 45,
    imageUrl: "https://images.unsplash.com/photo-1504941214544-9c1c44559ab4?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "תאורה לאירועים",
    location: "מרכז",
    suitableFor: ["concept-2", "concept-5", "concept-6", "concept-13"]
  },
  // ברים ומשקאות
  {
    id: "service8",
    name: "בר ניידת קוקטיילס",
    provider: "קוקטיילס בר",
    providerId: "provider8",
    description: "בר ניידת מקצועי עם ברמנים מנוסים ומבחר משקאות איכותיים",
    price: 3000,
    priceUnit: "לאירוע בסיסי",
    rating: 4.5,
    reviewCount: 76,
    imageUrl: "https://images.unsplash.com/photo-1470338950318-40320a722782?w=800&auto=format&fit=crop",
    category: "שירותי מזון ומשקאות",
    subcategory: "ברים ניידים",
    location: "מרכז",
    suitableFor: ["concept-2", "concept-5", "concept-6", "concept-13"]
  },
  {
    id: "service61",
    name: "ברמנים לאירועים",
    provider: "בר-מאסטר",
    providerId: "provider61",
    description: "ברמנים מקצועיים ומבחר קוקטיילים ייחודיים",
    price: 2500,
    priceUnit: "לאירוע",
    rating: 4.6,
    reviewCount: 58,
    imageUrl: "https://images.unsplash.com/photo-1516997121675-4c2d1684aa3e?w=800&auto=format&fit=crop",
    category: "שירותי מזון ומשקאות",
    subcategory: "ברמנים לאירועים",
    location: "ארצי",
    suitableFor: ["concept-2", "concept-5", "concept-6", "concept-13"]
  },
  // דוכני מזון
  {
    id: "service62",
    name: "דוכני מזון לאירועים",
    provider: "פוד קורנרס",
    providerId: "provider62",
    description: "מגוון דוכני מזון ייחודיים לשדרוג האירוע",
    price: 3500,
    priceUnit: "לדוכן",
    rating: 4.7,
    reviewCount: 64,
    imageUrl: "https://images.unsplash.com/photo-1505826759037-406b40feb4cd?w=800&auto=format&fit=crop",
    category: "שירותי מזון ומשקאות",
    subcategory: "דוכני מזון",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-8"]
  },
  {
    id: "service63",
    name: "דוכן גלידה איטלקית",
    provider: "ג'לאטו פרימו",
    providerId: "provider63",
    description: "דוכן גלידה איטלקית עם טעמים מיוחדים שנעשים במקום",
    price: 1800,
    priceUnit: "לאירוע",
    rating: 4.9,
    reviewCount: 47,
    imageUrl: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=800&auto=format&fit=crop",
    category: "שירותי מזון ומשקאות",
    subcategory: "דוכני מזון",
    location: "מרכז וצפון",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-8"]
  },
  // שפים פרטיים
  {
    id: "service64",
    name: "שף פרטי לאירועים",
    provider: "שף גורמה",
    providerId: "provider64",
    description: "שף פרטי המתמחה בארוחות גורמה לאירועים קטנים ויוקרתיים",
    price: 6000,
    priceUnit: "לאירוע עד 20 איש",
    rating: 4.9,
    reviewCount: 38,
    imageUrl: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=800&auto=format&fit=crop",
    category: "שירותי מזון ומשקאות",
    subcategory: "שפים פרטיים",
    location: "מרכז",
    suitableFor: ["concept-2", "concept-5", "concept-6", "concept-7"]
  },
  // סדנאות וימי גיבוש
  {
    id: "service10",
    name: "סדנת שוקולד",
    provider: "שוקולאב",
    providerId: "provider10",
    description: "סדנה חווייתית להכנת פרליני שוקולד, מתאימה לאירועי גיבוש וימי כיף",
    price: 1800,
    priceUnit: "ל-20 משתתפים",
    rating: 4.8,
    reviewCount: 54,
    imageUrl: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "סדנאות בישול",
    location: "מרכז",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-8"]
  },
  {
    id: "service12",
    name: "יום גיבוש אתגרי",
    provider: "אקסטרים טיולים",
    providerId: "provider12",
    description: "יום גיבוש מלא אתגר ואדרנלין, כולל פעילויות ODT ואתגרים קבוצתיים",
    price: 5000,
    priceUnit: "ל-20 משתתפים",
    rating: 4.7,
    reviewCount: 42,
    imageUrl: "https://images.unsplash.com/photo-1472162072942-cd5147eb3902?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "ימי גיבוש לחברות",
    location: "צפון",
    suitableFor: ["concept-4", "concept-5", "concept-11"]
  },
  {
    id: "service65",
    name: "סדנת בישול טבעוני",
    provider: "ירוק במטבח",
    providerId: "provider65",
    description: "סדנת בישול טבעוני לקבוצות וימי גיבוש",
    price: 2000,
    priceUnit: "ל-15 משתתפים",
    rating: 4.7,
    reviewCount: 29,
    imageUrl: "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "סדנאות בישול",
    location: "מרכז",
    suitableFor: ["concept-4", "concept-5", "concept-7"]
  },
  {
    id: "service66",
    name: "סדנת יצירה בזכוכית",
    provider: "זכוכית צבעונית",
    providerId: "provider66",
    description: "סדנת יצירה בזכוכית צבעונית לקבוצות",
    price: 1700,
    priceUnit: "ל-12 משתתפים",
    rating: 4.8,
    reviewCount: 31,
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "סדנאות ODT",
    location: "שפלה",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-7"]
  },
  // הופעות ובידור
  {
    id: "service67",
    name: "מופע סטנדאפ",
    provider: "צחוק לייב",
    providerId: "provider67",
    description: "מופע סטנדאפ מותאם אישית לאירועים",
    price: 3000,
    priceUnit: "למופע",
    rating: 4.6,
    reviewCount: 78,
    imageUrl: "https://images.unsplash.com/photo-1470019693664-1d202d2c0907?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "סטנדאפיסטים",
    location: "ארצי",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-8"]
  },
  {
    id: "service68",
    name: "מנחה אירועים מקצועי",
    provider: "יוסי המנחה",
    providerId: "provider68",
    description: "מנחה אירועים כריזמטי לכל סוגי האירועים",
    price: 2500,
    priceUnit: "לאירוע",
    rating: 4.8,
    reviewCount: 92,
    imageUrl: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "מנחי אירועים",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-4", "concept-5", "concept-6"]
  },
  {
    id: "service69",
    name: "מופע רקדנים",
    provider: "להקת הריקוד",
    providerId: "provider69",
    description: "מופע ריקוד מרהיב לאירועים",
    price: 3800,
    priceUnit: "למופע",
    rating: 4.7,
    reviewCount: 43,
    imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "רקדנים",
    location: "מרכז",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6"]
  },
  {
    id: "service70",
    name: "תקליטן לאירועים",
    provider: "די ג'יי גרוב",
    providerId: "provider70",
    description: "תקליטן מקצועי לכל סוגי האירועים עם ציוד הגברה ותאורה",
    price: 2800,
    priceUnit: "לאירוע",
    rating: 4.6,
    reviewCount: 118,
    imageUrl: "https://images.unsplash.com/photo-1571266028243-e4b018d5b936?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "תקליטנים",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-4", "concept-5", "concept-13"]
  },
  // טיולים וסיורים
  {
    id: "service71",
    name: "סיור יינות במרכז הארץ",
    provider: "יינות הארץ",
    providerId: "provider71",
    description: "סיור ביקבים באזור המרכז כולל טעימות וארוחה",
    price: 3500,
    priceUnit: "ל-15 משתתפים",
    rating: 4.9,
    reviewCount: 36,
    imageUrl: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "סיורים מודרכים",
    location: "מרכז",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-13"]
  },
  {
    id: "service72",
    name: "טיול ג'יפים בדרום",
    provider: "ג'יפאוט",
    providerId: "provider72",
    description: "טיולי ג'יפים אתגריים בנגב ובמצפה רמון",
    price: 4500,
    priceUnit: "ל-3 ג'יפים",
    rating: 4.8,
    reviewCount: 52,
    imageUrl: "https://images.unsplash.com/photo-1505015920881-0f83c2f9c5ca?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "טיולי ג'יפים",
    location: "דרום",
    suitableFor: ["concept-4", "concept-5", "concept-11"]
  },
  {
    id: "service73",
    name: "השכרת אופניים וסיור",
    provider: "ישראל על גלגלים",
    providerId: "provider73",
    description: "השכרת אופניים וסיורים מודרכים באזורים יפים בארץ",
    price: 2500,
    priceUnit: "ל-15 משתתפים",
    rating: 4.7,
    reviewCount: 39,
    imageUrl: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "טיולי אופניים",
    location: "צפון ומרכז",
    suitableFor: ["concept-4", "concept-5", "concept-11"]
  },
  // פעילויות אקסטרים
  {
    id: "service74",
    name: "רפטינג בצפון",
    provider: "כיף מים",
    providerId: "provider74",
    description: "פעילות רפטינג מאתגרת בנהר הירדן",
    price: 3200,
    priceUnit: "ל-15 משתתפים",
    rating: 4.8,
    reviewCount: 75,
    imageUrl: "https://images.unsplash.com/photo-1588860515286-814729319480?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "אטרקציות מים",
    location: "צפון",
    suitableFor: ["concept-4", "concept-5", "concept-11"]
  },
  {
    id: "service75",
    name: "סנפלינג וטיפוס צוקים",
    provider: "אדרנלין הפקות",
    providerId: "provider75",
    description: "פעילות סנפלינג וטיפוס צוקים בהדרכה מקצועית",
    price: 3800,
    priceUnit: "ל-15 משתתפים",
    rating: 4.9,
    reviewCount: 41,
    imageUrl: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "פעילויות אקסטרים",
    location: "מרכז וצפון",
    suitableFor: ["concept-4", "concept-5", "concept-11"]
  },
  // חדרי בריחה ופעילויות
  {
    id: "service76",
    name: "חדר בריחה נייד",
    provider: "אסקייפ מובייל",
    providerId: "provider76",
    description: "חדר בריחה נייד שמגיע אליכם לכל מקום",
    price: 2500,
    priceUnit: "לחדר ל-3 שעות",
    rating: 4.7,
    reviewCount: 48,
    imageUrl: "https://images.unsplash.com/photo-1569861568837-c15732ab38e3?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "חדרי בריחה",
    location: "ארצי",
    suitableFor: ["concept-4", "concept-5", "concept-7", "concept-8"]
  },
  // שירותי הסעות
  {
    id: "service77",
    name: "הסעות יוקרה לאירועים",
    provider: "לימוזין ישראל",
    providerId: "provider77",
    description: "שירותי הסעה יוקרתיים ללימוזינות ורכבי פאר",
    price: 1200,
    priceUnit: "לשעתיים",
    rating: 4.8,
    reviewCount: 56,
    imageUrl: "https://images.unsplash.com/photo-1609520505218-7421df2e7786?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "הסעות מאורגנות",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-13"]
  },
  {
    id: "service78",
    name: "הסעות קבוצתיות",
    provider: "אוטובוס לכל מטרה",
    providerId: "provider78",
    description: "הסעות בכל גודל לטיולים מאורגנים וימי כיף",
    price: 1500,
    priceUnit: "ליום",
    rating: 4.6,
    reviewCount: 38,
    imageUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "הסעות מאורגנות",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-4", "concept-5", "concept-11"]
  },
  // הרצאות
  {
    id: "service79",
    name: "הרצאת העצמה",
    provider: "שחר המרצה",
    providerId: "provider79",
    description: "הרצאת העצמה והנעה לפעולה לארגונים וחברות",
    price: 3500,
    priceUnit: "להרצאה",
    rating: 4.9,
    reviewCount: 87,
    imageUrl: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "העשרה",
    location: "ארצי",
    suitableFor: ["concept-4", "concept-5", "concept-7"]
  },
  // מופעי אש ולייזר
  {
    id: "service80",
    name: "מופע אש מרהיב",
    provider: "פיירשואו",
    providerId: "provider80",
    description: "מופע אש מרהיב לאירועים ומסיבות",
    price: 2800,
    priceUnit: "למופע",
    rating: 4.8,
    reviewCount: 43,
    imageUrl: "https://images.unsplash.com/photo-1551361995-69fe4c673401?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "מופעי אש",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-13"]
  },
  {
    id: "service81",
    name: "מופע לייזרים",
    provider: "לייזר ארט",
    providerId: "provider81",
    description: "מופע לייזרים מרהיב עם אפקטים ומוזיקה",
    price: 3500,
    priceUnit: "למופע",
    rating: 4.7,
    reviewCount: 29,
    imageUrl: "https://images.unsplash.com/photo-1549834125-80f9dda633c2?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "מופעי לייזר",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-10"]
  },
  // אוהלים ואירוח בשטח
  {
    id: "service82",
    name: "אוהלים לאירועים",
    provider: "אוהלי שמחה",
    providerId: "provider82",
    description: "אוהלים איכותיים בגדלים שונים לאירועים בשטח",
    price: 3500,
    priceUnit: "לאירוע בסיסי",
    rating: 4.6,
    reviewCount: 37,
    imageUrl: "https://images.unsplash.com/photo-1493306454986-c8877a09cbeb?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "אוהלים לאירועים",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-4", "concept-5"]
  },
  // הפקות
  {
    id: "service9",
    name: "הפקת אירועים טוטאל",
    provider: "טוטאל הפקות",
    providerId: "provider9",
    description: "הפקה מלאה של אירועים עסקיים, כולל ציוד טכני, קייטרינג ותכנים",
    price: 15000,
    priceUnit: "לאירוע בסיסי",
    rating: 4.9,
    reviewCount: 29,
    imageUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "מפיקי אירועים",
    location: "כל הארץ",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-10"],
    featured: true
  },
  {
    id: "service83",
    name: "הפקת אירועים פרטיים",
    provider: "חלום הפקות",
    providerId: "provider83",
    description: "הפקה מלאה של אירועים פרטיים - חתונות, בר/בת מצווה וימי הולדת",
    price: 8000,
    priceUnit: "לאירוע בסיסי",
    rating: 4.8,
    reviewCount: 64,
    imageUrl: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "מפיקי אירועים",
    location: "מרכז",
    suitableFor: ["concept-1", "concept-2", "concept-8"]
  },
  // אמני חושים נוספים
  {
    id: "service84",
    name: "מופע אמן חושים - מאיה הקוסמת",
    provider: "מאיה הקוסמת",
    providerId: "provider84",
    description: "מופע קסמים וקריאת מחשבות מרהיב ואינטראקטיבי",
    price: 3000,
    priceUnit: "למופע",
    rating: 4.8,
    reviewCount: 42,
    imageUrl: "https://images.unsplash.com/photo-1612103198005-b1f1a4f86990?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "אמני חושים",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-4", "concept-5", "concept-8"]
  },
  {
    id: "service85",
    name: "מופע מנטליזם - דורון רוזן",
    provider: "דורון רוזן",
    providerId: "provider85",
    description: "מופע קריאת מחשבות מותאם לאירועים עסקיים",
    price: 3200,
    priceUnit: "למופע",
    rating: 4.9,
    reviewCount: 38,
    imageUrl: "https://images.unsplash.com/photo-1529333166437-7cea30f76a32?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "אמני חושים",
    location: "מרכז וצפון",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-10"]
  }
];

// Expanded mock provider profiles
export const expandedMockProviders: ProviderProfile[] = [
  // נטע ברסלר - אמן חושים
  {
    id: "provider1",
    userId: "user1",
    businessName: "נטע ברסלר - מנטליסט",
    description: "נטע ברסלר, אמן חושים ומנטליסט מוביל בתחומו, מעניק מופעי מנטליזם וקריאת מחשבות מרתקים לכל סוגי האירועים.",
    contactPerson: "נטע ברסלר",
    email: "netta@mentalist.co.il",
    phone: "052-1234567",
    address: "רוטשילד 45",
    city: "תל אביב",
    categories: ["מופעים ואמנים"],
    logo: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=800&auto=format&fit=crop"
    ],
    rating: 4.9,
    reviewCount: 124,
    featured: true,
    verified: true
  },
  // קליספרו - אמן חושים
  {
    id: "provider4",
    userId: "user4",
    businessName: "קליספרו - קסמים ואשליות",
    description: "קליספרו מביא את אומנות הקסמים והאשליות לרמה חדשה עם מופעים מרתקים ומפתיעים שמתאימים לכל גיל ולכל סוג של אירוע.",
    contactPerson: "דן קליספרו",
    email: "info@calispro.co.il",
    phone: "050-9876543",
    address: "הרצל 78",
    city: "רעננה",
    categories: ["מופעים ואמנים"],
    logo: "https://images.unsplash.com/photo-1535979863199-3c77338429a0?w=800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1517263904808-5dc91e3e7044?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1560932033-2e51ae59158c?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1618944847828-82e943c3bdb7?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1575318634028-6a0cfcb60c4b?w=800&auto=format&fit=crop"
    ],
    rating: 4.9,
    reviewCount: 92,
    featured: true,
    verified: true
  },
  // אמני חושים נוספים
  {
    id: "provider84",
    userId: "user84",
    businessName: "מאיה הקוסמת",
    description: "מאיה הקוסמת מספקת חוויות קסם ופליאה באירועים פרטיים ועסקיים. המופע שלה משלב קסמים קלאסיים ומודרניים עם אלמנטים של קריאת מחשבות.",
    contactPerson: "מאיה לוין",
    email: "maya@magician.co.il",
    phone: "053-7654321",
    address: "גולדה מאיר 15",
    city: "חיפה",
    categories: ["מופעים ואמנים"],
    logo: "https://images.unsplash.com/photo-1575318634028-6a0cfcb60c4b?w=800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1604079628040-94301bb21b91?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1612103198005-b1f1a4f86990?w=800&auto=format&fit=crop"
    ],
    rating: 4.8,
    reviewCount: 42,
    featured: false,
    verified: true
  },
  {
    id: "provider85",
    userId: "user85",
    businessName: "דורון רוזן - מנטליסט",
    description: "דורון רוזן מביא את אמנות המנטליזם וקריאת המחשבות לאירועים עסקיים ופרטיים. המופע מותאם במיוחד לאווירה של אירועי חברה ועסקים.",
    contactPerson: "דורון רוזן",
    email: "doron@mentalist.co.il",
    phone: "054-8765432",
    address: "הארבעה 12",
    city: "תל אביב",
    categories: ["מופעים ואמנים"],
    logo: "https://images.unsplash.com/photo-1529333166437-7cea30f76a32?w=800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1537511446984-935f663eb1f4?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1579389083078-4e7018379f7e?w=800&auto=format&fit=crop"
    ],
    rating: 4.9,
    reviewCount: 38,
    featured: false,
    verified: true
  },
  // להקות ונגנים
  {
    id: "provider2",
    userId: "user2",
    businessName: "מלודי מייקרס - להקה לאירועים",
    description: "להקה מקצועית המתמחה באירועים פרטיים ועסקיים, עם רפרטואר עשיר במגוון סגנונות מוזיקליים.",
    contactPerson: "אבי כהן",
    email: "info@melodymakers.co.il",
    phone: "054-7654321",
    address: "שדרות ירושלים 35",
    city: "יפו",
    categories: ["מופעים ואמנים"],
    logo: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1501612780327-45045538702b?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1499364615650-ec38552f4f34?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1461784180009-21121b2f204c?w=800&auto=format&fit=crop"
    ],
    rating: 4.8,
    reviewCount: 87,
    verified: true
  },
  // זמרת
  {
    id: "provider51",
    userId: "user51",
    businessName: "שיר ישראלי - זמרת לאירועים",
    description: "זמרת מקצועית עם ניסיון עשיר בהופעות באירועים פרטיים ועסקיים",
    contactPerson: "שיר ישראלי",
    email: "shir@singer.co.il",
    phone: "052-3456789",
    address: "הנביאים 15",
    city: "ירושלים",
    categories: ["מופעים ואמנים"],
    logo: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop"
    ],
    rating: 4.7,
    reviewCount: 63,
    verified: true
  },
  // רביעיית מיתרים
  {
    id: "provider52",
    userId: "user52",
    businessName: "רביעיית אלגרו",
    description: "רביעיית מיתרים קלאסית לאירועים יוקרתיים ואלגנטיים",
    contactPerson: "רון לוי",
    email: "quartet@allegro.co.il",
    phone: "050-8765432",
    address: "רוטשילד 123",
    city: "תל אביב",
    categories: ["מופעים ואמנים"],
    logo: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1533470192478-9897d1a8eb89?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1465821185615-20b3c2fbf41b?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1461784121038-f088ca1e7714?w=800&auto=format&fit=crop"
    ],
    rating: 4.9,
    reviewCount: 41,
    verified: true
  },
  // קייטרינג ושירותי מזון
  {
    id: "provider3",
    userId: "user3",
    businessName: "מעדני גורמה - קייטרינג",
    description: "קייטרינג גורמה לאירועים יוקרתיים עם התמחות במטבח בינלאומי ומקומי איכותי.",
    contactPerson: "יוסי לוי",
    email: "info@gourmet-catering.co.il",
    phone: "03-6543210",
    address: "החשמונאים 12",
    city: "תל אביב",
    categories: ["שירותי מזון ומשקאות"],
    logo: "https://images.unsplash.com/photo-1555244162-803834f70033?w=800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop"
    ],
    rating: 4.7,
    reviewCount: 156,
    verified: true
  }
];

// Expanded mock reviews for various providers
export const expandedMockReviews: Review[] = [
  // ביקורות לנטע ברסלר
  {
    id: "review1",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user2",
    userName: "מיכל לוי",
    userAvatar: "https://randomuser.me/api/portraits/women/44.jpg",
    rating: 5,
    comment: "נטע הופיע באירוע החברה שלנו והדהים את כולם! מומלץ בחום!",
    date: "2023-05-15",
    created_at: "2023-05-15T10:00:00Z",
    updated_at: "2023-05-15T10:00:00Z",
    verified: true
  },
  {
    id: "review2",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user3",
    userName: "דוד כהן",
    userAvatar: "https://randomuser.me/api/portraits/men/22.jpg",
    rating: 5,
    comment: "היה מדהים בבר מצווה של הבן שלנו. המופע היה מותאם מושלם לאירוע ולגיל הילדים.",
    date: "2023-04-02",
    created_at: "2023-04-02T14:30:00Z",
    updated_at: "2023-04-02T14:30:00Z",
    verified: true
  },
  {
    id: "review3",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user4",
    userName: "סיגל אברהם",
    rating: 4,
    comment: "מופע מרשים מאוד ומקצועי. היחס היה נהדר וההתאמה לאירוע הייתה טובה מאוד.",
    date: "2023-03-12",
    created_at: "2023-03-12T16:45:00Z",
    updated_at: "2023-03-12T16:45:00Z",
    verified: true
  },
  {
    id: "review4",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user5",
    userName: "אלון שמיר",
    userAvatar: "https://randomuser.me/api/portraits/men/67.jpg",
    rating: 5,
    comment: "אין מילים לתאר כמה המופע של נטע היה מדהים. הוא קרא מחשבות, ניחש פרטים אישיים והשאיר את כולם בהלם מוחלט. אחד הדברים הכי מרשימים שראיתי!",
    date: "2023-01-25",
    created_at: "2023-01-25T19:20:00Z",
    updated_at: "2023-01-25T19:20:00Z",
    verified: true
  },
  // ביקורות לקליספרו
  {
    id: "review5",
    serviceId: "service4",
    providerId: "provider4",
    userId: "user6",
    userName: "תמר אוחנה",
    userAvatar: "https://randomuser.me/api/portraits/women/33.jpg",
    rating: 5,
    comment: "קליספרו הופיע ביום הולדת 50 של בעלי והפתיע את כולם. מומלץ בחום!",
    date: "2023-06-10",
    created_at: "2023-06-10T18:00:00Z",
    updated_at: "2023-06-10T18:00:00Z",
    verified: true
  },
  {
    id: "review6",
    serviceId: "service4",
    providerId: "provider4",
    userId: "user7",
    userName: "אייל גולן",
    userAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
    rating: 5,
    comment: "המופע היה משעשע ומפתיע, הקסמים מרשימים והאווירה מעולה. כל האורחים נהנו.",
    date: "2023-05-22",
    created_at: "2023-05-22T20:30:00Z",
    updated_at: "2023-05-22T20:30:00Z",
    verified: true
  }
];
