
import { SearchResultService, ProviderProfile, Review } from "@/lib/types";

// Mock search results
export const mockSearchResults: SearchResultService[] = [
  {
    id: "service1",
    name: "אומנות המנטליזם עם נטע ברסלר",
    provider: "נטע ברסלר",
    providerId: "provider1",
    description: "מופע מרהיב של קריאת מחשבות ומנטליזם מותאם לאירועים עסקיים ופרטיים",
    price: 3500,
    priceUnit: "לאירוע",
    rating: 4.9,
    reviewCount: 124,
    imageUrl: "https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "אמני חושים",
    location: "מרכז",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-8"],
    featured: true
  },
  {
    id: "service2",
    name: "להקת מלודי מייקרס",
    provider: "מלודי מייקרס",
    providerId: "provider2",
    description: "להקה מקצועית לאירועים עם רפרטואר עשיר וביצועים מרהיבים",
    price: 4500,
    priceUnit: "לאירוע",
    rating: 4.8,
    reviewCount: 87,
    imageUrl: "https://images.unsplash.com/photo-1501612780327-45045538702b?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "להקות",
    location: "כל הארץ",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6"]
  },
  {
    id: "service3",
    name: "קייטרינג מעדני גורמה",
    provider: "מעדני גורמה",
    providerId: "provider3",
    description: "חוויה קולינרית עשירה לאירועים בכל סדר גודל עם תפריט מגוון ומיוחד",
    price: 120,
    priceUnit: "למנה",
    rating: 4.7,
    reviewCount: 156,
    imageUrl: "https://images.unsplash.com/photo-1555244162-803834f70033?w=800&auto=format&fit=crop",
    category: "שירותי מזון ומשקאות",
    subcategory: "קייטרינג בשרי",
    location: "מרכז וירושלים",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6", "concept-8"]
  },
  {
    id: "service4",
    name: "קליוסטרו - קסמים ואשליות",
    provider: "דן קליוסטרו",
    providerId: "provider4",
    description: "מופע קסמים מדהים ואינטראקטיבי לכל הגילאים",
    price: 2800,
    priceUnit: "לאירוע",
    rating: 4.9,
    reviewCount: 92,
    imageUrl: "https://images.unsplash.com/photo-1537074142379-4ce9d4cd7901?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "קוסמים",
    location: "כל הארץ",
    suitableFor: ["concept-1", "concept-3", "concept-5", "concept-8"],
    featured: true
  },
  {
    id: "service5",
    name: "עיצובי פרחים פנטזיה",
    provider: "פנטזיה עיצובים",
    providerId: "provider5",
    description: "עיצובי פרחים מרהיבים וייחודיים לכל אירוע",
    price: 1500,
    priceUnit: "בסיס לאירוע",
    rating: 4.6,
    reviewCount: 68,
    imageUrl: "https://images.unsplash.com/photo-1561128290-e900944315fe?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "עיצוב פרחים",
    location: "צפון ומרכז",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6"]
  },
  {
    id: "service6",
    name: "יעקב הצלם",
    provider: "יעקב כהן",
    providerId: "provider6",
    description: "צילום מקצועי לאירועים פרטיים ועסקיים, כולל עריכה מלאה",
    price: 2200,
    priceUnit: "לאירוע",
    rating: 4.8,
    reviewCount: 112,
    imageUrl: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "צילום סטילס",
    location: "כל הארץ",
    suitableFor: ["concept-1", "concept-2", "concept-3", "concept-5", "concept-8"]
  },
  {
    id: "service7",
    name: "לופט תל אביב",
    provider: "לופט TLV",
    providerId: "provider7",
    description: "לופט מעוצב בלב תל אביב, מתאים לאירועים פרטיים ועסקיים עד 100 איש",
    price: 7000,
    priceUnit: "ליום",
    rating: 4.7,
    reviewCount: 43,
    imageUrl: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&auto=format&fit=crop",
    category: "לוקיישנים ומתחמי אירוח",
    subcategory: "לופטים",
    location: "תל אביב",
    suitableFor: ["concept-4", "concept-5", "concept-7"]
  },
  {
    id: "service8",
    name: "בר ניידת קוקטיילס",
    provider: "קוקטיילס בר",
    providerId: "provider8",
    description: "בר ניידת מקצועי עם ברמנים מנוסים ומבחר משקאות איכותיים",
    price: 3000,
    priceUnit: "לאירוע בסיסי",
    rating: 4.5,
    reviewCount: 76,
    imageUrl: "https://images.unsplash.com/photo-1470338950318-40320a722782?w=800&auto=format&fit=crop",
    category: "שירותי מזון ומשקאות",
    subcategory: "ברים ניידים",
    location: "מרכז",
    suitableFor: ["concept-2", "concept-5", "concept-6", "concept-13"]
  },
  {
    id: "service9",
    name: "הפקת אירועים טוטאל",
    provider: "טוטאל הפקות",
    providerId: "provider9",
    description: "הפקה מלאה של אירועים עסקיים, כולל ציוד טכני, קייטרינג ותכנים",
    price: 15000,
    priceUnit: "לאירוע בסיסי",
    rating: 4.9,
    reviewCount: 29,
    imageUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "מפיקי אירועים",
    location: "כל הארץ",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-10"],
    featured: true
  },
  {
    id: "service10",
    name: "סדנת שוקולד",
    provider: "שוקולאב",
    providerId: "provider10",
    description: "סדנה חווייתית להכנת פרליני שוקולד, מתאימה לאירועי גיבוש וימי כיף",
    price: 1800,
    priceUnit: "ל-20 משתתפים",
    rating: 4.8,
    reviewCount: 54,
    imageUrl: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "סדנאות בישול",
    location: "מרכז",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-8"]
  },
  {
    id: "service11",
    name: "צלמות מגנטים לאירועים",
    provider: "מגנטיקס",
    providerId: "provider11",
    description: "צילומי מגנטים מיוחדים לאירועים עם מגוון אביזרים ורקעים",
    price: 1200,
    priceUnit: "לשעתיים",
    rating: 4.6,
    reviewCount: 87,
    imageUrl: "https://images.unsplash.com/photo-1552334823-ca7f70361452?w=800&auto=format&fit=crop",
    category: "מתנות",
    subcategory: "מגנטים וצילומי מגנט",
    location: "כל הארץ",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-13"]
  },
  {
    id: "service12",
    name: "יום גיבוש אתגרי",
    provider: "אקסטרים טיולים",
    providerId: "provider12",
    description: "יום גיבוש מלא אתגר ואדרנלין, כולל פעילויות ODT ואתגרים קבוצתיים",
    price: 5000,
    priceUnit: "ל-20 משתתפים",
    rating: 4.7,
    reviewCount: 42,
    imageUrl: "https://images.unsplash.com/photo-1472162072942-cd5147eb3902?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "ימי גיבוש לחברות",
    location: "צפון",
    suitableFor: ["concept-4", "concept-5", "concept-11"]
  }
];

// Mock provider profiles
export const mockProviders: ProviderProfile[] = [
  {
    id: "provider1",
    userId: "user1",
    businessName: "נטע ברסלר - מנטליסט",
    description: "נטע ברסלר, אמן חושים ומנטליסט מוביל בתחומו, מעניק מופעי מנטליזם וקריאת מחשבות מרתקים לכל סוגי האירועים.",
    contactPerson: "נטע ברסלר",
    email: "netta@mentalist.co.il",
    phone: "052-1234567",
    address: "רוטשילד 45",
    city: "תל אביב",
    categories: ["מופעים ואמנים"],
    logo: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=800&auto=format&fit=crop"
    ],
    rating: 4.9,
    reviewCount: 124,
    featured: true,
    verified: true
  }
];

// Mock reviews for a provider
export const mockReviews: Review[] = [
  {
    id: "review1",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user2",
    userName: "מיכל לוי",
    userAvatar: "https://randomuser.me/api/portraits/women/44.jpg",
    rating: 5,
    comment: "נטע הופיע באירוע החברה שלנו והדהים את כולם! מומלץ בחום!",
    date: "2023-05-15",
    verified: true
  },
  {
    id: "review2",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user3",
    userName: "דוד כהן",
    userAvatar: "https://randomuser.me/api/portraits/men/22.jpg",
    rating: 5,
    comment: "היה מדהים בבר מצווה של הבן שלנו. המופע היה מותאם מושלם לאירוע ולגיל הילדים.",
    date: "2023-04-02",
    verified: true
  },
  {
    id: "review3",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user4",
    userName: "סיגל אברהם",
    rating: 4,
    comment: "מופע מרשים מאוד ומקצועי. היחס היה נהדר וההתאמה לאירוע הייתה טובה מאוד.",
    date: "2023-03-12",
    verified: true
  },
  {
    id: "review4",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user5",
    userName: "אלון שמיר",
    userAvatar: "https://randomuser.me/api/portraits/men/67.jpg",
    rating: 5,
    comment: "אין מילים לתאר כמה המופע של נטע היה מדהים. הוא קרא מחשבות, ניחש פרטים אישיים והשאיר את כולם בהלם מוחלט. אחד הדברים הכי מרשימים שראיתי!",
    date: "2023-01-25",
    verified: true
  }
];
