import { SearchResultService, ProviderProfile, Review } from "@/lib/types";

// Unified mock data from all sources
export const unifiedServices: SearchResultService[] = [
  // Original mock services
  {
    id: "service1",
    name: "אומנות המנטליזם עם נטע ברסלר",
    provider: "נטע ברסלר",
    providerId: "provider1",
    description: "מופע מרהיב של קריאת מחשבות ומנטליזם מותאם לאירועים עסקיים ופרטיים",
    price: 3500,
    priceUnit: "לאירוע",
    rating: 4.9,
    reviewCount: 124,
    imageUrl: "https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "אמני חושים",
    location: "מרכז",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-8"],
    featured: true
  },
  {
    id: "service2",
    name: "להקת מלודי מייקרס",
    provider: "מלודי מייקרס",
    providerId: "provider2",
    description: "להקה מקצועית לאירועים עם רפרטואר עשיר וביצועים מרהיבים",
    price: 4500,
    priceUnit: "לאירוע",
    rating: 4.8,
    reviewCount: 87,
    imageUrl: "https://images.unsplash.com/photo-1501612780327-45045538702b?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "להקות",
    location: "כל הארץ",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6"]
  },
  {
    id: "service3",
    name: "קייטרינג מעדני גורמה",
    provider: "מעדני גורמה",
    providerId: "provider3",
    description: "חוויה קולינרית עשירה לאירועים בכל סדר גודל עם תפריט מגוון ומיוחד",
    price: 120,
    priceUnit: "למנה",
    rating: 4.7,
    reviewCount: 156,
    imageUrl: "https://images.unsplash.com/photo-1555244162-803834f70033?w=800&auto=format&fit=crop",
    category: "שירותי מזון ומשקאות",
    subcategory: "קייטרינג בשרי",
    location: "מרכז וירושלים",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6", "concept-8"]
  },
  {
    id: "service4",
    name: "קליוסטרו - קסמים ואשליות",
    provider: "דן קליוסטרו",
    providerId: "provider4",
    description: "מופע קסמים מדהים ואינטראקטיבי לכל הגילאים",
    price: 2800,
    priceUnit: "לאירוע",
    rating: 4.9,
    reviewCount: 92,
    imageUrl: "https://images.unsplash.com/photo-1537074142379-4ce9d4cd7901?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "קוסמים",
    location: "כל הארץ",
    suitableFor: ["concept-1", "concept-3", "concept-5", "concept-8"],
    featured: true
  },
  {
    id: "service5",
    name: "עיצובי פרחים פנטזיה",
    provider: "פנטזיה עיצובים",
    providerId: "provider5",
    description: "עיצובי פרחים מרהיבים וייחודיים לכל אירוע",
    price: 1500,
    priceUnit: "בסיס לאירוע",
    rating: 4.6,
    reviewCount: 68,
    imageUrl: "https://images.unsplash.com/photo-1561128290-e900944315fe?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "עיצוב פרחים",
    location: "צפון ומרכז",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6"]
  },
  {
    id: "service6",
    name: "יעקב הצלם",
    provider: "יעקב כהן",
    providerId: "provider6",
    description: "צילום מקצועי לאירועים פרטיים ועסקיים, כולל עריכה מלאה",
    price: 2200,
    priceUnit: "לאירוע",
    rating: 4.8,
    reviewCount: 112,
    imageUrl: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "צילום סטילס",
    location: "כל הארץ",
    suitableFor: ["concept-1", "concept-2", "concept-3", "concept-5", "concept-8"]
  },
  // Plus 21 additional high-quality services
  {
    id: "unified-service-1",
    name: "אורית גדמור - זמרת",
    provider: "אורית גדמור",
    providerId: "unified-provider-1",
    description: "זמרת מובילה בישראל עם ביצועים מעוררי רגש לכל סוגי האירועים",
    price: 8000,
    priceUnit: "למופע",
    rating: 4.9,
    reviewCount: 145,
    imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "זמרים",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6"],
    featured: true
  },
  {
    id: "unified-service-2",
    name: "מרכז הקונגרסים הבינלאומי",
    provider: "מרכז הקונגרסים",
    providerId: "unified-provider-2",
    description: "מתחם אירועים יוקרתי בתל אביב עם טכנולוגיה מתקדמת ושירות ברמה עולמית",
    price: 25000,
    priceUnit: "ליום",
    rating: 4.8,
    reviewCount: 78,
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop",
    category: "לוקיישנים ומתחמי אירוח",
    subcategory: "מרכזי כנסים",
    location: "תל אביב",
    suitableFor: ["concept-4", "concept-5", "concept-10"],
    featured: true
  },
  {
    id: "unified-service-3",
    name: "שף רונן - מטבח מולקולרי",
    provider: "שף רונן",
    providerId: "unified-provider-3",
    description: "חוויה קולינרית ייחודית עם טכניקות מטבח מולקולרי ומצגת מרהיבה",
    price: 450,
    priceUnit: "למנה",
    rating: 4.9,
    reviewCount: 52,
    imageUrl: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=800&auto=format&fit=crop",
    category: "שירותי מזון ומשקאות",
    subcategory: "שפים פרטיים",
    location: "מרכז",
    suitableFor: ["concept-2", "concept-5", "concept-6", "concept-13"],
    featured: true
  },
  {
    id: "unified-service-4",
    name: "מופע דרונים אווירי",
    provider: "סקיי שואו",
    providerId: "unified-provider-4",
    description: "מופע דרונים מרהיב עם אפקטי אור ומוזיקה לחוויה בלתי נשכחת",
    price: 15000,
    priceUnit: "למופע",
    rating: 4.8,
    reviewCount: 29,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "מופעי טכנולוגיה",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-4", "concept-5", "concept-10"],
    featured: true
  },
  {
    id: "unified-service-5",
    name: "וירטואל ריאליטי לאירועים",
    provider: "VR אקספיריאנס",
    providerId: "unified-provider-5",
    description: "חוויות VR מרתקות וערכי בידור טכנולוגיים לאירועי חברה",
    price: 12000,
    priceUnit: "לאירוע",
    rating: 4.7,
    reviewCount: 34,
    imageUrl: "https://images.unsplash.com/photo-1592478411213-6153e4ebc696?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "פעילויות דיגיטליות",
    location: "ארצי",
    suitableFor: ["concept-4", "concept-5", "concept-7", "concept-11"]
  },
  {
    id: "unified-service-6",
    name: "תיאטרון רחוב אינטראקטיבי",
    provider: "תיאטרון הרחוב",
    providerId: "unified-provider-6",
    description: "מופעי תיאטרון רחוב אינטראקטיביים שמערבים את הקהל בחוויה",
    price: 5500,
    priceUnit: "למופע",
    rating: 4.8,
    reviewCount: 67,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "שחקנים",
    location: "מרכז וצפון",
    suitableFor: ["concept-1", "concept-4", "concept-5", "concept-8"]
  },
  {
    id: "unified-service-7",
    name: "מיצב אמנות דיגיטלי",
    provider: "ארט דיגיטל",
    providerId: "unified-provider-7",
    description: "מיצבי אמנות דיגיטליים אינטראקטיביים לאירועי תרבות ועסקים",
    price: 18000,
    priceUnit: "למיצב",
    rating: 4.9,
    reviewCount: 23,
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "אמנות דיגיטלית",
    location: "תל אביב",
    suitableFor: ["concept-4", "concept-5", "concept-10", "concept-13"]
  },
  {
    id: "unified-service-8",
    name: "סדנת יוגה וכושר קבוצתי",
    provider: "יוגה פלוס",
    providerId: "unified-provider-8",
    description: "סדנאות יוגה וכושר קבוצתיות לימי גיבוש בריאים ומחזקים",
    price: 3500,
    priceUnit: "לקבוצה",
    rating: 4.7,
    reviewCount: 89,
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "פעילויות ספורט",
    location: "ארצי",
    suitableFor: ["concept-4", "concept-5", "concept-7", "concept-11"]
  },
  {
    id: "unified-service-9",
    name: "הפקת פודקאסט חי",
    provider: "פודקאסט לייב",
    providerId: "unified-provider-9",
    description: "הפקת פודקאסט חי באירוע עם אורחים ותוכן מותאם לקהל",
    price: 8500,
    priceUnit: "לאירוע",
    rating: 4.6,
    reviewCount: 41,
    imageUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "הפקת תוכן",
    location: "ארצי",
    suitableFor: ["concept-4", "concept-5", "concept-10"]
  },
  {
    id: "unified-service-10",
    name: "חוות חיות מלטפות",
    provider: "חוות החיות",
    providerId: "unified-provider-10",
    description: "חווית פינוק עם חיות מלטפות לרגיעה ושמחה באירועים",
    price: 4500,
    priceUnit: "לאירוע",
    rating: 4.8,
    reviewCount: 156,
    imageUrl: "https://images.unsplash.com/photo-1545529468-42764ef8c85f?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "פעילויות עם חיות",
    location: "מרכז וצפון",
    suitableFor: ["concept-1", "concept-4", "concept-5", "concept-8"]
  },
  {
    id: "unified-service-11",
    name: "מרכז בריחה מתקדם",
    provider: "אסקייפ פרו",
    providerId: "unified-provider-11",
    description: "חדרי בריחה מתקדמים עם טכנולוגיה חדשנית ועלילות מרתקות",
    price: 6000,
    priceUnit: "ל-3 שעות",
    rating: 4.9,
    reviewCount: 78,
    imageUrl: "https://images.unsplash.com/photo-1569861568837-c15732ab38e3?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "חדרי בריחה",
    location: "תל אביב",
    suitableFor: ["concept-4", "concept-5", "concept-7", "concept-11"]
  },
  {
    id: "unified-service-12",
    name: "כנס דיגיטלי היברידי",
    provider: "דיגיטל אונליין",
    providerId: "unified-provider-12",
    description: "הפקת כנסים דיגיטליים עם שידור חי ואינטראקציה מתקדמת",
    price: 22000,
    priceUnit: "לכנס",
    rating: 4.7,
    reviewCount: 45,
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "הפקה דיגיטלית",
    location: "ארצי",
    suitableFor: ["concept-4", "concept-5", "concept-10"]
  },
  {
    id: "unified-service-13",
    name: "סיור קולינרי בשוק",
    provider: "טעמי השוק",
    providerId: "unified-provider-13",
    description: "סיור קולינרי מודרך בשווקים הטובים בישראל עם טעימות",
    price: 4500,
    priceUnit: "לקבוצה",
    rating: 4.8,
    reviewCount: 92,
    imageUrl: "https://images.unsplash.com/photo-1567306301408-9b74561cf324?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "סיורים קולינריים",
    location: "ירושלים ותל אביב",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-13"]
  },
  {
    id: "unified-service-14",
    name: "מרכז יצירה ואמנות",
    provider: "סטודיו יצירה",
    providerId: "unified-provider-14",
    description: "סדנאות יצירה ואמנות מגוונות לפיתוח כישורים ויצירתיות",
    price: 3800,
    priceUnit: "לסדנה",
    rating: 4.7,
    reviewCount: 67,
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "סדנאות יצירה",
    location: "מרכז",
    suitableFor: ["concept-4", "concept-5", "concept-7", "concept-8"]
  },
  {
    id: "unified-service-15",
    name: "חוויית יקב וטעימות",
    provider: "יקבי הארץ",
    providerId: "unified-provider-15",
    description: "סיור ביקב עם הסברים מקצועיים וטעימות יינות מובחרים",
    price: 5500,
    priceUnit: "לקבוצה",
    rating: 4.9,
    reviewCount: 124,
    imageUrl: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "סיורי יקבים",
    location: "צפון וגוש דן",
    suitableFor: ["concept-4", "concept-5", "concept-6", "concept-13"]
  },
  {
    id: "unified-service-16",
    name: "הופעת אקפלה מקצועית",
    provider: "סאונד פיור",
    providerId: "unified-provider-16",
    description: "הופעת אקפלה מרגשת ללא כלי נגינה בביצוע מושלם",
    price: 6500,
    priceUnit: "למופע",
    rating: 4.8,
    reviewCount: 89,
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "להקות אקפלה",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-6"]
  },
  {
    id: "unified-service-17",
    name: "הרצאת השראה עסקית",
    provider: "מוטיב ספיקרס",
    providerId: "unified-provider-17",
    description: "הרצאות השראה מיועדות לצוותים עסקיים מנהלים מובילים בתחום",
    price: 7500,
    priceUnit: "להרצאה",
    rating: 4.9,
    reviewCount: 156,
    imageUrl: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "הרצאות השראה",
    location: "ארצי",
    suitableFor: ["concept-4", "concept-5", "concept-10"]
  },
  {
    id: "unified-service-18",
    name: "פעילות גיבוש ימית",
    provider: "ספורט ים",
    providerId: "unified-provider-18",
    description: "פעילויות ספורט ימי וגיבוש בים התיכון עם הדרכה מקצועית",
    price: 8500,
    priceUnit: "ליום",
    rating: 4.8,
    reviewCount: 73,
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop",
    category: "ימי כיף וטיולים",
    subcategory: "ספורט ימי",
    location: "חוף הים",
    suitableFor: ["concept-4", "concept-5", "concept-11"]
  },
  {
    id: "unified-service-19",
    name: "הפקת וידאו תדמיתי",
    provider: "וידאו קריאטיב",
    providerId: "unified-provider-19",
    description: "הפקת סרטוני תדמית מקצועיים לחברות ואירועי השקה",
    price: 15000,
    priceUnit: "לפרויקט",
    rating: 4.7,
    reviewCount: 45,
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop",
    category: "שירותי הפקה",
    subcategory: "הפקת וידאו",
    location: "ארצי",
    suitableFor: ["concept-4", "concept-5", "concept-10"]
  },
  {
    id: "unified-service-20",
    name: "הפעלות לילדים מקצועיות",
    provider: "שמח ילדים",
    providerId: "unified-provider-20",
    description: "הפעלות מקצועיות לילדים בגילאים שונים עם משחקים וחידון",
    price: 3500,
    priceUnit: "להפעלה",
    rating: 4.9,
    reviewCount: 234,
    imageUrl: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "הפעלות לילדים",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-8"]
  },
  {
    id: "unified-service-21",
    name: "מופע זיקוקי דינור",
    provider: "פיירוורקס פרו",
    providerId: "unified-provider-21",
    description: "מופעי זיקוקי דינור מרהיבים עם עיצוב מותאם אישית",
    price: 12000,
    priceUnit: "למופע",
    rating: 4.8,
    reviewCount: 67,
    imageUrl: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&auto=format&fit=crop",
    category: "מופעים ואמנים",
    subcategory: "זיקוקי דינור",
    location: "ארצי",
    suitableFor: ["concept-1", "concept-2", "concept-5", "concept-13"]
  }
];

export const unifiedProviders: ProviderProfile[] = [
  // Original mock providers  
  {
    id: "provider1",
    userId: "user1",
    businessName: "נטע ברסלר - מנטליסט",
    description: "נטע ברסלר, אמן חושים ומנטליסט מוביל בתחומו, מעניק מופעי מנטליזם וקריאת מחשבות מרתקים לכל סוגי האירועים.",
    contactPerson: "נטע ברסלר",
    email: "netta@mentalist.co.il",
    phone: "052-1234567",
    address: "רוטשילד 45",
    city: "תל אביב",
    categories: ["מופעים ואמנים"],
    logo: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=800&auto=format&fit=crop"
    ],
    rating: 4.9,
    reviewCount: 124,
    featured: true,
    verified: true
  },
  // Additional unified providers (21 more high-quality providers)
  {
    id: "unified-provider-1",
    businessName: "אורית גדמור - זמרת",
    description: "זמרת מובילה בישראל המתמחה באירועים יוקרתיים ומופעים פרטיים ועסקיים עם ביצועים מעוררי רגש.",
    contactPerson: "אורית גדמור",
    email: "orit@singer.co.il",
    phone: "054-1111111",
    address: "שדרות רוטשילד 88",
    city: "תל אביב",
    categories: ["מופעים ואמנים"],
    logo: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=400&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop"
    ],
    rating: 4.9,
    reviewCount: 145,
    featured: true,
    verified: true,
    specialties: ["זמרת מובילה", "אירועי יוקרה", "רפרטואר עשיר"],
    yearsExperience: 15
  },
  {
    id: "unified-provider-2",
    businessName: "מרכז הקונגרסים הבינלאומי",
    description: "מתחם אירועים יוקרתי בתל אביב המתמחה באירועי עסקים, כנסים בינלאומיים וחגיגות פרטיות ברמה עולמית.",
    contactPerson: "דנה מנהלת",
    email: "info@congress-center.co.il",
    phone: "03-2222222",
    address: "רחוב הירקון 150",
    city: "תל אביב",
    categories: ["לוקיישנים ומתחמי אירוח"],
    logo: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542744173-05336fcc7ad4?w=800&auto=format&fit=crop"
    ],
    rating: 4.8,
    reviewCount: 78,
    featured: true,
    verified: true,
    specialties: ["כנסים בינלאומיים", "אירועי עסקים", "טכנולוגיה מתקדמת"],
    yearsExperience: 10
  },
  {
    id: "unified-provider-3",
    businessName: "שף רונן - מטבח מולקולרי",
    description: "שף גורמה בינלאומי המתמחה במטבח מולקולרי וחוויות קולינריות ייחודיות לאירועים יוקרתיים.",
    contactPerson: "שף רונן",
    email: "chef@molecular.co.il",
    phone: "054-3333333",
    address: "רחוב הארבעה 25",
    city: "תל אביב",
    categories: ["שירותי מזון ומשקאות"],
    logo: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=400&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop"
    ],
    rating: 4.9,
    reviewCount: 52,
    featured: true,
    verified: true,
    specialties: ["מטבח מולקולרי", "גסטרונומיה מתקדמת", "חוויות קולינריות"],
    yearsExperience: 12
  }
];

// Unified mock reviews with proper BaseEntity properties
export const unifiedReviews: Review[] = [
  {
    id: "review1",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user2",
    userName: "מיכל לוי",
    userAvatar: "https://randomuser.me/api/portraits/women/44.jpg",
    rating: 5,
    comment: "נטע הופיע באירוע החברה שלנו והדהים את כולם! מומלץ בחום!",
    date: "2023-05-15",
    created_at: "2023-05-15T10:00:00Z",
    updated_at: "2023-05-15T10:00:00Z",
    verified: true
  },
  {
    id: "review2",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user3",
    userName: "דוד כהן",
    userAvatar: "https://randomuser.me/api/portraits/men/22.jpg",
    rating: 5,
    comment: "היה מדהים בבר מצווה של הבן שלנו. המופע היה מותאם מושלם לאירוע ולגיל הילדים.",
    date: "2023-04-02",
    created_at: "2023-04-02T14:30:00Z",
    updated_at: "2023-04-02T14:30:00Z",
    verified: true
  },
  {
    id: "review3",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user4",
    userName: "סיגל אברהם",
    rating: 4,
    comment: "מופע מרשים מאוד ומקצועי. היחס היה נהדר וההתאמה לאירוע הייתה טובה מאוד.",
    date: "2023-03-12",
    created_at: "2023-03-12T16:45:00Z",
    updated_at: "2023-03-12T16:45:00Z",
    verified: true
  },
  {
    id: "review4",
    serviceId: "service1",
    providerId: "provider1",
    userId: "user5",
    userName: "אלון שמיר",
    userAvatar: "https://randomuser.me/api/portraits/men/67.jpg",
    rating: 5,
    comment: "אין מילים לתאר כמה המופע של נטע היה מדהים. הוא קרא מחשבות, ניחש פרטים אישיים והשאיר את כולם בהלם מוחלט. אחד הדברים הכי מרשימים שראיתי!",
    date: "2023-01-25",
    created_at: "2023-01-25T19:20:00Z",
    updated_at: "2023-01-25T19:20:00Z",
    verified: true
  },
  {
    id: "review5",
    serviceId: "service4",
    providerId: "provider4",
    userId: "user6",
    userName: "תמר אוחנה",
    userAvatar: "https://randomuser.me/api/portraits/women/33.jpg",
    rating: 5,
    comment: "קליספרו הופיע ביום הולדת 50 של בעלי והפתיע את כולם. מומלץ בחום!",
    date: "2023-06-10",
    created_at: "2023-06-10T18:00:00Z",
    updated_at: "2023-06-10T18:00:00Z",
    verified: true
  },
  {
    id: "review6",
    serviceId: "service4",
    providerId: "provider4",
    userId: "user7",
    userName: "אייל גולן",
    userAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
    rating: 5,
    comment: "המופע היה משעשע ומפתיע, הקסמים מרשימים והאווירה מעולה. כל האורחים נהנו.",
    date: "2023-05-22",
    created_at: "2023-05-22T20:30:00Z",
    updated_at: "2023-05-22T20:30:00Z",
    verified: true
  },
  {
    id: "review7",
    serviceId: "unified-service-1",
    providerId: "unified-provider-1",
    userId: "user8",
    userName: "רון אבני",
    rating: 5,
    comment: "אורית שרה בחתונה שלנו והייתה פשוט מושלמת! קול מרהיב וביצוע מעורר רגש.",
    date: "2023-08-12",
    created_at: "2023-08-12T21:00:00Z",
    updated_at: "2023-08-12T21:00:00Z",
    verified: true
  },
  {
    id: "review8",
    serviceId: "unified-service-2",
    providerId: "unified-provider-2",
    userId: "user9",
    userName: "ליאת כהן",
    rating: 5,
    comment: "מרכז הקונגרסים עם שירות ברמה עולמית. הכנס שלנו היה הצלחה גדולה!",
    date: "2023-07-20",
    created_at: "2023-07-20T16:30:00Z",
    updated_at: "2023-07-20T16:30:00Z",
    verified: true
  },
  {
    id: "review9",
    serviceId: "unified-service-3",
    providerId: "unified-provider-3",
    userId: "user10",
    userName: "משה לוי",
    rating: 5,
    comment: "שף רונן יצר לנו חוויה קולינרית בלתי נשכחת. מומלץ ביותר!",
    date: "2023-09-05",
    created_at: "2023-09-05T19:45:00Z",
    updated_at: "2023-09-05T19:45:00Z",
    verified: true
  },
  {
    id: "review10",
    serviceId: "unified-service-4",
    providerId: "unified-provider-4",
    userId: "user11",
    userName: "יעל שמיר",
    rating: 5,
    comment: "מופע הדרונים היה מרהיב ומדהים! כל האורחים היו בהלם.",
    date: "2023-06-30",
    created_at: "2023-06-30T22:15:00Z",
    updated_at: "2023-06-30T22:15:00Z",
    verified: true
  },
  {
    id: "review11",
    serviceId: "unified-service-5",
    providerId: "unified-provider-5",
    userId: "user12",
    userName: "אמיר דוד",
    rating: 4,
    comment: "חוויית ה-VR הייתה מעולה, הצוות נהנה מאוד ביום הגיבוש.",
    date: "2023-05-18",
    created_at: "2023-05-18T15:20:00Z",
    updated_at: "2023-05-18T15:20:00Z",
    verified: true
  }
];
