// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnkkcpmdfpsktgrljytg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhua2tjcG1kZnBza3RncmxqeXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDYwNTAsImV4cCI6MjA2MjkyMjA1MH0.0qpqjnsXF0ux4NM-R8oJQ0Miquw1ciAHcY-eM0-6qN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);